/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AtPassportApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AtPassportSessions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AtPassportShareTokens": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SessionSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}